# .gitlab-ci.yml

# Prevents pipeline execution everywhere but staging/production
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "staging" || $CI_COMMIT_BRANCH == "production"
      when: always
    - when: never

# Load environment configs
include:
  - local: '.gitlab/workflows/deployment.yml'
  - local: '.gitlab/config/staging.yml'
  - local: '.gitlab/config/production.yml'

default:
  image: thecodingmachine/php:8.3-v4-cli-node20

stages:
  - Deployment

# Staging Deployment
Deployment Staging:
  extends:
    - .base_job
    - .staging_config
    - .deployment_script
  stage: Deployment
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      when: always
    - when: never

# Production Deployment
Deployment Production:
  extends:
    - .base_job
    - .production_config
    - .deployment_script
  stage: Deployment
  rules:
    - if: '$CI_COMMIT_BRANCH == "production"'
      when: always
    - when: never